pom.xml, src/main/java/org/dcsa/tnt/model/TransportCall.java
Bump Core version to 0.7.1
Move VesselIMONumber validation to Core
=> Use the Core defined validation on VesselIMONumber

pom.xml
=> Bump spring-boot and dcsa-core

.github/workflows/microservices.yml, pom.xml, src/main/java/org/dcsa/tnt/repository/EquipmentEventRepository.java, src/main/java/org/dcsa/tnt/repository/EventSubscriptionRepository.java, src/main/java/org/dcsa/tnt/repository/ShipmentEventRepository.java, src/main/java/org/dcsa/tnt/repository/TransportEventRepository.java, src/main/java/org/dcsa/tnt/service/EquipmentEventService.java, src/main/java/org/dcsa/tnt/service/ShipmentEventService.java, src/main/java/org/dcsa/tnt/service/TransportEventService.java, src/main/java/org/dcsa/tnt/service/impl/EquipmentEventServiceImpl.java, src/main/java/org/dcsa/tnt/service/impl/EventSubscriptionServiceImpl.java, src/main/java/org/dcsa/tnt/service/impl/ShipmentEventServiceImpl.java, src/main/java/org/dcsa/tnt/service/impl/TransportEventServiceImpl.java, src/main/java/org/dcsa/tnt/util/EventCallbackHandler.java
* REST Assured is a test framework - not a production client. Replace it with Spring WebClient.
* Add validation of URLs before saving event subscriptions (to stop obvious errors early)
* Remove hardcoded schema name to simplify moving to a new schema (e.g. `dcsa_im_v3_0`)
=> Refactor of TNT

src/main/resources/application.yaml
=> Rename dcsa_ebl_v1_0 to dcsa_im_v3_0

pom.xml, src/main/java/org/dcsa/tnt/model/EquipmentEvent.java, src/main/java/org/dcsa/tnt/model/Event.java, src/main/java/org/dcsa/tnt/model/ShipmentEvent.java, src/main/java/org/dcsa/tnt/util/ExtendedEventRequest.java
=> Update TNT match core changes

pom.xml, src/main/java/org/dcsa/tnt/controller/EventController.java, src/main/java/org/dcsa/tnt/util/ExtendedEventRequest.java
=> Update to match recent core changes

.github/workflows/microservices.yml, src/main/resources/application.yaml
=> Improve error reporting for CI

src/main/java/org/dcsa/tnt/model/EquipmentEvent.java, src/main/java/org/dcsa/tnt/model/TransportEvent.java, src/main/java/org/dcsa/tnt/service/EventSubscriptionService.java, src/main/java/org/dcsa/tnt/service/impl/EventSubscriptionServiceImpl.java, src/main/java/org/dcsa/tnt/util/ExtendedEventRequest.java
=> Use transportDocumentReference

pom.xml, src/main/java/org/dcsa/tnt/Application.java, src/main/java/org/dcsa/tnt/controller/EventController.java, src/main/java/org/dcsa/tnt/controller/EventSubscriptionTOController.java
=> Removed swagger annotations and dependency

pom.xml
Part of issue : dcsaorg/DCSA-Core#79
=> Separated dcsa.tag to dcsa.core.tag & dcsa.event.tag

pom.xml
Part of issue :  dcsaorg/DCSA-Core#79
=> renamed dcsa versions and artifacttype

.github/workflows/microservices.yml
=> CI: Refer to DCSA-API-Validator master branch again

.github/workflows/microservices.yml, pom.xml
=> Bump DCSA-Event-Core and IM version

.github/workflows/microservices.yml
=> Use API-Validator master branch again

pom.xml
=> DDT-144: Bump event core to fix sorting issue

pom.xml
Delete dependency from tnt as it is in core now
=> DDT-248 Spring actuator dependency moved to core

src/main/resources/application.yaml
To be able to route calls to tnt in sandbox project
=> DDT-867 Add Url prefix env variable

.dockerignore, .github/workflows/microservices.yml, .gitignore, Dockerfile, pom.xml
=> Upgrade to JDK 17

tnt-persistence/src/main/java/org/dcsa/tnt/persistence/entity/EquipmentEvent.java, tnt-persistence/src/main/java/org/dcsa/tnt/persistence/repository/SealRepository.java, tnt-service/src/main/java/org/dcsa/tnt/service/SealService.java, tnt-service/src/test/java/org/dcsa/tnt/service/mapping/EventFieldsTest.java
- This is done through UtilizedEquipmentID which is defined in the IM on an equipment event
=> DDT-1233:  Look up seals for events

tnt-persistence/src/main/java/org/dcsa/tnt/persistence/entity/Equipment.java
=> Add `@Builder` to Equipment

tnt-application/src/main/resources/application.yml
Signed-off-by: Niels Thykier <nit@globeteam.com>
=> DDT-1438: Correct specification version

tnt-application/src/main/java/org/dcsa/tnt/controller/EventController.java, tnt-persistence/src/main/java/org/dcsa/tnt/persistence/entity/EventSubscription.java, tnt-persistence/src/main/java/org/dcsa/tnt/persistence/entity/Service.java, tnt-transfer-obj/src/main/java/org/dcsa/tnt/transferobjects/EventSubscriptionTO.java
Dependent on [IM #405](https://github.com/dcsaorg/DCSA-Information-Model/pull/405)
=> DDT-1469: update carrier service code max length
